# Generated by Django 4.0.4 on 2022-04-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name=' ')),
                ('first_name', models.CharField(max_length=15, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=15, verbose_name='last_name')),
                ('address', models.CharField(max_length=15, verbose_name='address')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password1', models.DecimalField(decimal_places=10, max_digits=100000000000, verbose_name='password')),
                ('phone_number', models.IntegerField(max_length=11, verbose_name='phone_number')),
            ],
        ),
    ]
