# Generated by Django 4.0.4 on 2022-04-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_information_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='name')),
                ('first_name', models.CharField(max_length=15, verbose_name='first_name')),
            ],
        ),
        migrations.AlterField(
            model_name='information',
            name='username',
            field=models.CharField(max_length=15, verbose_name='name'),
        ),
    ]
